# Generated by Django 4.2.2 on 2023-06-10 16:10

import Modelos.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Discapacidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=13)),
                ('nombres', models.CharField(max_length=60)),
                ('apellidos', models.CharField(max_length=60)),
                ('foto_perfil', models.FileField(blank=True, null=True, upload_to='fotoEstudiantes/%Y')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('correo', models.EmailField(blank=True, max_length=100, null=True)),
                ('celular', models.CharField(blank=True, max_length=10, null=True)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('ciudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Modelos.ciudad')),
                ('discapacidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Modelos.discapacidad')),
                ('estado_civil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Modelos.estadocivil')),
            ],
        ),
        migrations.CreateModel(
            name='Etnia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ModalidadEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('abreviatura', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='NumeroMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('capital', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Paralelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Parentezco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TiposAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=13)),
                ('nombres', models.CharField(max_length=60)),
                ('apellidos', models.CharField(max_length=60)),
                ('celular', models.CharField(blank=True, max_length=10, null=True)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('ciudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Modelos.ciudad')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modelos.estudiante')),
                ('pais', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Modelos.pais')),
                ('parentezco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Modelos.parentezco')),
                ('provincia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Modelos.provincia')),
            ],
        ),
        migrations.CreateModel(
            name='InformacionAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('numero_carne', models.CharField(blank=True, max_length=10, null=True)),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Modelos.estado')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modelos.estudiante')),
                ('jornada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Modelos.jornada')),
                ('modalidad_estudios', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Modelos.modalidadestudio')),
                ('numero_matricula', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Modelos.numeromatricula')),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='etnia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Modelos.etnia'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='genero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Modelos.genero'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='pais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Modelos.pais'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='provincia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Modelos.provincia'),
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Modelos.especialidad')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Modelos.estado')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modelos.estudiante')),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Modelos.grado')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Modelos.nivel')),
                ('paralelo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Modelos.paralelo')),
                ('periodo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Modelos.periodo')),
            ],
        ),
        migrations.AddField(
            model_name='ciudad',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Modelos.provincia'),
        ),
        migrations.CreateModel(
            name='Anexos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=Modelos.models.Anexos.ruta_personalizada)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modelos.estudiante')),
                ('periodo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Modelos.periodo')),
                ('tipo_anexo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Modelos.tiposanexo')),
            ],
        ),

        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=13)),
                ('nombres', models.CharField(max_length=60)),
                ('apellidos', models.CharField(max_length=60)),
                ('foto_perfil', models.FileField(blank=True, null=True, upload_to='fotoDocentes/%Y')),
                ('nivel_educacion', models.CharField(max_length=60)),
                ('titulo_tercer_nivel', models.CharField(max_length=60)),
                ('titulo_cuarto_nivel', models.CharField(max_length=60)),
                ('especialidad', models.CharField(max_length=60)),
                ('grupo_etnico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Modelos.etnia')),
                ('relacion_laboral', models.CharField(max_length=100)),
                ('funcion_cargo', models.CharField(max_length=60)),
                ('funcion_2', models.CharField(max_length=60)),
                ('categoria', models.CharField(max_length=60)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('edad', models.CharField(max_length=60)),
                ('fecha_ingreso_magisterio', models.DateField(blank=True, null=True)),
                ('anos_servicio_magisterio', models.CharField(max_length=60)),
                ('fecha_ingreso_ie', models.DateField(blank=True, null=True)),
                ('anos_servicio_ie', models.CharField(max_length=60)),
                ('lugar_recidencia', models.CharField(max_length=60)),
                ('celular', models.CharField(max_length=60)),
                ('correo', models.EmailField(max_length=60)),
                ('correo_institucional', models.EmailField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
