# Generated by Django 4.2.5 on 2023-09-19 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='anos_servicio_ie',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='anos_servicio_magisterio',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='categoria',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='celular',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='correo',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='edad',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='especialidad',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='funcion_2',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='funcion_cargo',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='lugar_recidencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Modelos.ciudad'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='nivel_educacion',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='relacion_laboral',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='titulo_cuarto_nivel',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='titulo_tercer_nivel',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
