# Generated by Django 4.2.5 on 2023-09-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0002_alter_docente_anos_servicio_ie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='lugar_recidencia',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
