# Generated by Django 4.2.2 on 2023-06-10 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('correo', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Inicio.rol')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
